on: [push]
name: build
jobs:
  runhaskell:
    name: agda2scala
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [9.10.1] # [9.6.6, 9.8.2, 9.10.1]
    steps:
      - name: Checks-out repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up GHC
        uses: haskell-actions/setup@cd0d9bdd65b20557f41bea4dbe43d0b5fbbfe553 # v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.10.3'
          cabal-update: true

      - name: Set up HLint
        uses: haskell-actions/hlint-setup@fe9cd1cd1af94a23900c06738e73f6ddb092966a # v2

      - name: Check with HLint
        uses: haskell-actions/hlint-run@eaca4cfbf4a69f4eb875df38b6bc3e1657020378 # v2
        with:
          path: '["src/", "app/", "test/"]'
          fail-on: warning

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('dist-newstyle/cache/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: cabal build all --only-dependencies

      - name: Install Agda standard library
        run: |
          git clone --depth 1 --branch v2.4 https://github.com/agda/agda-stdlib.git "$HOME/agda-stdlib"
          mkdir -p "$HOME/.config/agda"
          echo "$HOME/agda-stdlib/standard-library.agda-lib" > "$HOME/.config/agda/libraries"
          echo "standard-library" > "$HOME/.config/agda/defaults"
          cat "$HOME/.config/agda/libraries"
          cat "$HOME/.config/agda/defaults"

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Save cached dependencies
        uses: actions/cache/save@caa296126883cff596d87d8935842f9db880ef25 # v5
        # If we had an exact cache hit, trying to save the cache would error because of key clash.
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Run Haskell tests
        run: cabal test all

      - name: Compile example Agda code to Scala 2
        run: |
          cabal run -- agda2scala --scala-dialect=Scala2 --out-dir=scala2/src/main/scala ./examples/adts.agda
          cabal run -- agda2scala --scala-dialect=Scala2 --out-dir=scala2/src/main/scala ./examples/rbt.agda

      - name: Compile example Agda code to Scala 3
        run: |
          cabal run -- agda2scala --out-dir=scala3/src/main/scala ./examples/adts.agda
          cabal run -- agda2scala --out-dir=scala3/src/main/scala ./examples/rbt.agda

      - name: Set up JVM
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'
      - name: Set up Scala and SBT
        uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1
      - name: compile & test result Scala 2 code
        run: sbt ";clean;testFull"
        working-directory: ./scala2
      - name: compile & test result Scala 3 code
        run: sbt ";clean;testFull"
        working-directory: ./scala3
