on: [push]
name: build
jobs:
  runhaskell:
    name: agda2scala
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [9.10.1] # [9.6.6, 9.8.2, 9.10.1]
    steps:
      - name: Checks-out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up GHC
        uses: haskell-actions/setup@cd0d9bdd65b20557f41bea4dbe43d0b5fbbfe553 # v2
        id: setup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: '3.10.3'
          cabal-update: true

      - name: Configure the build
        run: |
          cabal configure --enable-tests --enable-benchmarks --disable-documentation
          cabal build --dry-run
        # The last step generates dist-newstyle/cache/plan.json for the cache key.

      - name: Restore cached dependencies
        uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        id: cache
        env:
          key: ${{ runner.os }}-ghc-${{ steps.setup.outputs.ghc-version }}-cabal-${{ steps.setup.outputs.cabal-version }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-plan-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}-

      - name: Install dependencies
        # If we had an exact cache hit, the dependencies will be up to date.
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: cabal build all --only-dependencies

      # Cache dependencies already here, so that we do not have to rebuild them should the subsequent steps fail.
      - name: Save cached dependencies
        uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
        # If we had an exact cache hit, trying to save the cache would error because of key clash.
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build
        run: cabal build all

      - name: Run Haskell tests
        run: cabal test all

      - name: Compile example Agda code to Scala 2
        run: cabal run -- agda2scala --out-dir=scala2/src/main/scala ./examples/adts.agda

      - name: Compile example Agda code to Scala 3
        run: cabal run -- agda2scala --scala-dialect=Scala3 --out-dir=scala3/src/main/scala ./examples/adts.agda

      - name: Set up JVM
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Set up Scala and SBT
        uses: sbt/setup-sbt@508b753e53cb6095967669e0911487d2b9bc9f41 # v1
      - name: compile & test result Scala 2 code
        run: sbt clean test
        working-directory: ./scala2
      - name: compile & test result Scala 3 code
        run: sbt clean test
        working-directory: ./scala3
